### ISSUE TITLE
Im newbie learning a lot, can u explain

### ISSUE THREAD

**Issue by taliafranco** [mareksuscak/cs50#3]
Hi Marek,

Im very new to this, can u explain from line 30 to 36. From my understanding, (cc_number % 10 = digit1) is to obtain the last number(if im not mistaken)? But why is digit2 = digit1? and why sum_of_even +=digit1? I look forward for your reply and would greatly appreciate a detailed explanation. Thanks!

**Comment by mareksuscak** [comment]
@taliafranco Oops, just noticed this issue. 

> From my understanding, (cc_number % 10 = digit1) is to obtain the last number(if im not mistaken)?

That's right.

> But why is digit2 = digit1?

The key to understanding how this works is right below that line — since digit1 is assigned AFTER its value's assigned to digit2, it means it will always contain the value of digit1 from the previous loop iteration. Therefore, after completing all iterations it will hold last but one value processed — the second digit since we progress from the end to the start of the number.

> and why sum_of_even += digit1?

I assume you're referring to the following lines of code:

https://github.com/mareksuscak/cs50/blob/b2324e29a4692b2d53750da7fb95ebc20248e728/pset1/credit/credit.c#L33-L36

According to [the algorithm description](https://docs.cs50.net/2018/x/psets/1/credit/credit.html#background), point number 2 and the relevant portion of the point number 1:

> 1. **Multiply every other digit by 2**, starting with the number’s second-to-last digit, and then add those products' digits together.
> 2. **Add the sum to the sum of the digits that weren’t multiplied by 2.**
> 3. If the total’s last digit is 0 (or, put more formally, if the total modulo 10 is congruent to 0), the number is valid!

We need to add all digits that weren't multiplied by 2. According to the definition, the *other* digits are odd and those that were not multiplied by two must be even thereof.

Hope it helps.

**Comment by karkelley** [comment]
The problem I have with the explanation is that the generic word "it" is used too often. I cannot figure out which part "it" is referring to in each line. Some clarification here would help.

**Comment by rajan9519** [comment]
Will you please attach the file or code for which you wants explanation.
Thank you.

**Comment by karkelley** [comment]
https://github.com/mareksuscak/cs50/commit/5a6cad53b7db22eaf02b1710aa2c7ab83534748b

Thank you,
*Karen Kelley*
*IT, Computer Science,** and mathematics  departments*
Messalonskee High School
131 Messalonskee High Drive
Oakland, Maine 04963

*Messalonskee High School community fosters critical thinkers, *

*effective communicators, and creative problem solvers.*

**Comment by rajan9519** [comment]
// Many of you are probably wondering why digit2 = digit1.
// The key to understanding how this works is right below
// that line — since digit1 is assigned AFTER its value's
// assigned to digit2, that means digit2 will always contain
// the value of digit1 from the previous loop iteration.
// Therefore, after completing all iterations digit2 will
// hold last but one value processed — the second digit

Is it clear now?

**Comment by karkelley** [comment]
Much better. A couple more questions though:

   - // hold* last* *but one* value processed — the second digit (does
   'last' mean 'all'?)
   - I am assuming the digit1 and digit2 are the first and second digits at
   the left of the number. Is this correct?


Thank you,
*Karen Kelley*
*IT, Computer Science,** and mathematics  departments*
Messalonskee High School
131 Messalonskee High Drive
Oakland, Maine 04963

*Messalonskee High School community fosters critical thinkers, *

*effective communicators, and creative problem solvers.*

**Comment by rajan9519** [comment]
Yes like after some iteration on(say 4793)
digit1 will contain 4 and digt2 will contain 7 that is the previous value
of digit1 before the loop termination.
Thank you.

**Comment by karkelley** [comment]
Thank you very much for taking the time to clarify .

**Comment by rajan9519** [comment]
Pleasure is all mine.

**Comment by karkelley** [comment]
Hi,
I cannot get check50 to work. I have created my own repository and branch.
I have also added a file. The best I can get from check50 is "Did you mean
something else?" What am I doing wrong?

What should the path be for this file?
I have these instructions:  //check50 <owner>/<repo>/<branch>/<problem>

I have been entering:  check50 karkelley/master/pset2/caesar
and have also tried:  check50 karkelley/pset2/master/caesar

I followed instructions from this site:
https://cs50.readthedocs.io/projects/check50/en/latest/check_writer.html#creating-a-check-and-running-it

Thank you,
*Karen Kelley*
*IT, Computer Science,** and mathematics  departments*
Messalonskee High School
131 Messalonskee High Drive
Oakland, Maine 04963

*Messalonskee High School community fosters critical thinkers, *

*effective communicators, and creative problem solvers.*
